apiVersion: v1
kind: Service
metadata:
  name: keycloak-registration
spec:
  selector:
    app: keycloak-registration
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
